[package]
name = "note"
version = "0.1.0"
edition = "2021"

[dependencies]
select = '0.6.0'
uuid = { version = "0.8", features = ["v4"]}
serde = {version = "1.0",  features = ["derive", "std"]}
serde_json = "1.0"
